### ISSUE TITLE
Integration token expires without renewing

### ISSUE THREAD

**Issue by brendandixon** [lawtancool/hass-control4#14]
The integration periodically fails because the API token used when invoking C4 expires. A disable/enable of the integration renews the token and restores function. 

I suspect the API token comes with a readable expiry date. It'd be great if the integration could either renew the token before that date or renew the token upon receiving an expired token error from an API call.

I pulled the following from the logs:

`Evening Lights: Error executing script. Unexpected error for call_service at pos 1: { "error": "Unauthorized", "details": "Expired or invalid token" }
7:34:26 PM – (ERROR) Automation (custom integration) - message first occurred at 7:16:11 PM and shows up 4 times
`

**Comment by asafalfa** [comment]
the entire solution stop working ! Looks like a blocker!  :(



`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/control4/lock.py:124
Integration: Home Assistant WebSocket API
First occurred: 1:34:01 PM (7 occurrences)
Last logged: 1:37:17 PM

[139867099706176] { "error": "Unauthorized", "details": "Expired or invalid token" }
[139866917378240] { "error": "Unauthorized", "details": "Expired or invalid token" }
[139866899683520] { "error": "Unauthorized", "details": "Expired or invalid token" }
[139867098108224] { "error": "Unauthorized", "details": "Expired or invalid token" }
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
return await service.entity_service_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
response_data = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/lock/init.py", line 111, in _async_unlock
await entity.async_unlock(**remove_entity_service_fields(service_call))
File "/config/custom_components/control4/lock.py", line 124, in async_unlock
await c4_relay.close()
File "/usr/local/lib/python3.11/site-packages/pyControl4/relay.py", line 70, in close
await self.director.sendPostRequest(
File "/usr/local/lib/python3.11/site-packages/pyControl4/director.py", line 99, in sendPostRequest
await checkResponseForError(await resp.text())
File "/usr/local/lib/python3.11/site-packages/pyControl4/error_handling.py", line 114, in checkResponseForError
raise exception(response_text)
pyControl4.error_handling.BadToken: {
"error": "Unauthorized",
"details": "Expired or invalid token"
}`

**Comment by asafalfa** [comment]
anothe example from light.py 

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/control4/light.py:132
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 4:31:19 PM (3 occurrences)
Last logged: 5:47:30 PM

[139866916344512] { "error": "Unauthorized", "details": "Expired or invalid token" }
[139866717870400] { "error": "Unauthorized", "details": "Expired or invalid token" }
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 130, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 898, in entity_service_call
    task.result()  # pop exception if have
    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1199, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/control4/light.py", line 132, in async_turn_on
    await c4_light.rampToLevel(brightness, transition_length)
  File "/usr/local/lib/python3.11/site-packages/pyControl4/light.py", line 51, in rampToLevel
    await self.director.sendPostRequest(
  File "/usr/local/lib/python3.11/site-packages/pyControl4/director.py", line 99, in sendPostRequest
    await checkResponseForError(await resp.text())
  File "/usr/local/lib/python3.11/site-packages/pyControl4/error_handling.py", line 114, in checkResponseForError
    raise exception(response_text)
pyControl4.error_handling.BadToken: {
 "error": "Unauthorized",
 "details": "Expired or invalid token"
}

**Comment by asafalfa** [comment]
restart of home assistant fixing this

**Comment by brendandixon** [comment]
Whatever forces a refresh of the token will "fix" the problem. Restart, disable/enable, remove/install all should work.

**Comment by muhlman** [comment]
Also experiencing this, whats odd is I was running fine for a while, now it expires every day, not sure if c4 changed something on their end.

**Comment by brendandixon** [comment]
I believe what's occurring is the C4 servers are occasionally dropping connections. That breaks the read performed in getRefreshToken and it goes downhill from there. Here's a better log snippet:

`Traceback (most recent call last):
  File "/config/custom_components/control4/__init__.py", line 194, in refresh_tokens
    director_token_dict = await account.getDirectorBearerToken(controller_unique_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyControl4/account.py", line 234, in getDirectorBearerToken
    data = await self.__sendControllerAuthRequest(controller_common_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyControl4/account.py", line 137, in __sendControllerAuthRequest
    async with self.session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 601, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 965, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/control4/__init__.py", line 307, in refresh_tokens
    return await refresh_tokens(self.hass, self.entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/control4/__init__.py", line 196, in refresh_tokens
    raise ConfigEntryNotReady(exception) from exception
homeassistant.exceptions.ConfigEntryNotReady: Server disconnected`

If I'm correct, and I likely am since any forced refresh fixes the issue, then updating the refresh token time to try again would be useful. Possibly even a delay of just a few seconds might work as well. This appears to be a classic case of a server being busy (or something); clients should gracefully retry under such conditions (with a backoff of some kind).

**Comment by Rawr0** [comment]
> Also experiencing this, whats odd is I was running fine for a while, now it expires every day, not sure if c4 changed something on their end.

I'm seeing the same behaviour. It used to be occasional, and I could reload the integration to refresh the token and resolve the issue, but now it's expiring every day or two.

**Comment by brendandixon** [comment]
I've given up on this integration. The default C4 integration shipped in HA core *does not* suffer this problem. It experiences the same Server Disconnect, but continues to work. It is limited only C4 lights/switches, but that's all I have anyway.

Just FYI.

**Comment by ljump12** [comment]
Likewise, I'm seeing this every day or two, restart of HA fixes it. Is there any more permanent fix? It breaks all my automations.

**Comment by Rawr0** [comment]
@ljump12 I’ve managed to work around it by creating a daily automation that reloads C4. Use the “home assistant core integration: reload” service and then point it at one of your C4 entities.
