### ISSUE TITLE
Token expire 

### ISSUE THREAD

**Issue by asafalfa** [lawtancool/hass-control4#15]
Look like token were expired, and all solution righ tnow is not working unforthenetly 

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/control4/light.py:132
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 4:31:19 PM (3 occurrences)
Last logged: 5:47:30 PM

[139866916344512] { "error": "Unauthorized", "details": "Expired or invalid token" }
[139866717870400] { "error": "Unauthorized", "details": "Expired or invalid token" }
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 130, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 898, in entity_service_call
    task.result()  # pop exception if have
    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1199, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/control4/light.py", line 132, in async_turn_on
    await c4_light.rampToLevel(brightness, transition_length)
  File "/usr/local/lib/python3.11/site-packages/pyControl4/light.py", line 51, in rampToLevel
    await self.director.sendPostRequest(
  File "/usr/local/lib/python3.11/site-packages/pyControl4/director.py", line 99, in sendPostRequest
    await checkResponseForError(await resp.text())
  File "/usr/local/lib/python3.11/site-packages/pyControl4/error_handling.py", line 114, in checkResponseForError
    raise exception(response_text)
pyControl4.error_handling.BadToken: {
 "error": "Unauthorized",
 "details": "Expired or invalid token"
}

**Comment by asafalfa** [comment]
restart of home assistant fixing this
