### ISSUE TITLE
Can't setup Alarm and binary sensors

### ISSUE THREAD

**Issue by kknopper** [lawtancool/hass-control4#16]
When I try to configure the modes for my alarm system I get error logs in home assistant. This may be related to #2 

For my config options, my control4 instance has 4 options: Stay, Away, Instant, and Maximum and i have mapped them as such in the ui:

- away mode name: Away
- home mode name: Stay
- night mode name: Instant
- custom bypass mode name: (not set)
- vacation mode name: Maximum

Not sure if I am setting my config options correctly or there is something else needed to get this work. All other entities appear as expected (lights and locks).

My Control4 instance is on the following version: `3.1.3.574826-res (May 19 2020)`

# Errors

`Category sensors does not exist on this Control4 system, entities from this domain will not be setup.`
Logger: custom_components.control4
Source: custom_components/control4/__init__.py:168
Integration: Control4
First occurred: 2:02:01 PM (94 occurrences)

Category sensors does not exist on this Control4 system, entities from this domain will not be setup.
Traceback (most recent call last):
  File "/config/custom_components/control4/__init__.py", line 168, in get_items_of_category
    return_list = await director.getAllItemsByCategory(category)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyControl4/director.py", line 112, in getAllItemsByCategory
    return_list = await self.sendGetRequest(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyControl4/director.py", line 63, in sendGetRequest
    await checkResponseForError(await resp.text())
  File "/usr/local/lib/python3.11/site-packages/pyControl4/error_handling.py", line 123, in checkResponseForError
    raise exception(response_text)
pyControl4.error_handling.InvalidCategory: {
 "error": "Invalid category"
}

`Error while setting up control4 platform for alarm_control_panel`

Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:359
Integration: Alarm control panel (documentation, issues)
First occurred: 2:02:01 PM (94 occurrences)
Last logged: 2:52:01 PM

Error while setting up control4 platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/control4/alarm_control_panel.py", line 225, in async_setup_entry
    item_setup_info = await director.getItemSetup(item_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyControl4/director.py", line 135, in getItemSetup
    return await self.sendPostRequest(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyControl4/director.py", line 99, in sendPostRequest
    await checkResponseForError(await resp.text())
  File "/usr/local/lib/python3.11/site-packages/pyControl4/error_handling.py", line 123, in checkResponseForError
    raise exception(response_text)
pyControl4.error_handling.C4Exception: {
 "error": "Z6B[Z5e.h5t(...)] is not a function"
}

**Comment by granvillebarker** [comment]
The bug i fixed in getItemSetup on pyControl4 will fix the second error shown here.
