### ISSUE TITLE
Unable to open "Configuration Panel": 500 internal Server Error

### ISSUE THREAD

**Issue by deltamikeromeo** [lawtancool/hass-control4#30]
When attempting to open the configuration panel, I get the following error: "Error Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

Logs attached below. I don't have any alarms in control4 so I'm unsure why it is failing at that key.

2024-09-16 16:32:58.968 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry control4_hc800_000FFF580817 for control4
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/control4/__init__.py", line 123, in async_setup_entry
    await entry_data[CONF_DIRECTOR].getUiConfiguration()
  File "/usr/local/lib/python3.12/site-packages/pyControl4/director.py", line 303, in getUiConfiguration
    return await self.sendGetRequest("/api/v1/agents/ui_configuration")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyControl4/director.py", line 64, in sendGetRequest
    await checkResponseForError(await resp.text())
  File "/usr/local/lib/python3.12/site-packages/pyControl4/error_handling.py", line 98, in checkResponseForError
    dictionary = xmltodict.parse(response_text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: mismatched tag: line 6, column 2
2024-09-16 16:33:00.995 WARNING (event_thread_0) [sucks] Ping did not reach VacBot. Will retry.
2024-09-16 16:33:22.315 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 343, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/control4/config_flow.py", line 203, in async_step_init
    _LOGGER.debug(self.entry_data[CONF_ALARM_ARM_STATES])
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'alarm_arm_states'

**Comment by deltamikeromeo** [comment]
I think this is related to the recent 1.3 release. Please see below: 


2024-09-20 16:18:39.559 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f8ac4cd50>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'control4' at custom_components/control4/__init__.py, line 257: await entry_data[CONF_WEBSOCKET].sio_connect(director.director_bearer_token) (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please create a bug report at https://github.com/lawtancool/hass-control4/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "", line 198, in _run_module_as_main
  File "", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in 
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/control4/__init__.py", line 81, in async_setup_entry
    await refresh_tokens(hass, entry)
  File "/config/custom_components/control4/__init__.py", line 257, in refresh_tokens
    await entry_data[CONF_WEBSOCKET].sio_connect(director.director_bearer_token)
2024-09-20 16:18:41.008 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry control4_hc800_000FFF580817 for control4
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/control4/__init__.py", line 123, in async_setup_entry
    await entry_data[CONF_DIRECTOR].getUiConfiguration()
  File "/usr/local/lib/python3.12/site-packages/pyControl4/director.py", line 303, in getUiConfiguration
    return await self.sendGetRequest("/api/v1/agents/ui_configuration")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyControl4/director.py", line 64, in sendGetRequest
    await checkResponseForError(await resp.text())
  File "/usr/local/lib/python3.12/site-packages/pyControl4/error_handling.py", line 98, in checkResponseForError
    dictionary = xmltodict.parse(response_text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: mismatched tag: line 6, column 2

**Comment by deltamikeromeo** [comment]
Hi @lawtancool, please see above. I think there is an issue with the new bearer auth in the 1.3 release. 

From: https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
SSLContext.load_default_certs does blocking disk I/O to load the certificates from disk.

The following helpers ensure that the blocking I/O will happen in the executor:
- aiohttp: homeassistant.helpers.aiohttp_client.async_get_clientsession to create the aiohttp.ClientSession.
- httpx: homeassistant.helpers.httpx_client.get_async_client to create the httpx.AsyncClient.
- Generic SSL: homeassistant.util.ssl

**Comment by BeHappy2021** [comment]
I've also started having the same issue today. Removed the integration, rebooted, and have been unable to connect to Control4 since.

**Comment by deltamikeromeo** [comment]
Hey @BeHappy2021 did you already revert to 1.2.1? That should fix it for you until a new revision is released to address the problem.

**Comment by BeHappy2021** [comment]
Hi @deltamikeromeo I couldn't get the roll back to work. I tried restoring from a backup and uninstalling the integration and installing the new one. I decided to leave it overnight - in case I was hitting some kind of request limit on C4 - and tried again this morning. Restored a backup from 2 weeks ago with 1.3.0 and all working fine.

**Comment by browneye253** [comment]
I was hitting the same issue on 2024.10.4 and updated to 2024.11.1 and it resolved the error for me.

**Comment by deltamikeromeo** [comment]
I'm on 2025.1.4 and it is giving me that 500 Internal Server error on 1.3.0 again. This time with a different traceback error. Are you all still on 2024.11.1? 

2025-01-28 11:29:39.737 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 316, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 491, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/control4/config_flow.py", line 203, in async_step_init
    _LOGGER.debug(self.entry_data[CONF_ALARM_ARM_STATES])
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'alarm_arm_states'

**Comment by deltamikeromeo** [comment]
Fixed by downgrading to HA Core 2024.11.1 and C4 1.2.1. I tried both independently but only the double downgrade fixed it for me.

**Comment by cyberkryten** [comment]
I'm seeing the same but can't downgrade HA Core as other integrations stopped working on 2024 release that I need.

I think what is happening is that the initialisation is failing on the blocking call which means the data block isn't setup correctly so when the Config panel tries to use it, there's no alarm_arm_states entry to be read from.  

However, I can't quite figure out how to get around the blocking issue.

**Comment by deltamikeromeo** [comment]
@lawtancool do you have bandwidth to investigate this issue? I am not sure if you are able to reproduce our problem on your system. I can gather any extra debug info you think would be helpful.

**Comment by mellis** [comment]
I do see the warning regarding the blocking call but my system seems to be functioning still with 1.3.0 and latest HA version.

**Comment by deltamikeromeo** [comment]
I just tried updating again from 2024.11.1 to 2025.3.3 and I still get the error with all my C4 devices no longer responding. Anyone have ideas? I'm stuck on 2024.11.1 in this case.

2025-03-14 10:17:51.057 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry control4_hc800_000FFF580817 for control4
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 753, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/control4/__init__.py", line 135, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2560, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 1 more time]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1172, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1097, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1387, in _gcd_import
  File "", line 1360, in _find_and_load
  File "", line 1331, in _find_and_load_unlocked
  File "", line 935, in _load_unlocked
  File "", line 1026, in exec_module
  File "", line 488, in _call_with_frames_removed
  File "/config/custom_components/control4/alarm_control_panel.py", line 12, in 
    from homeassistant.components.alarm_control_panel import (
    ...<4 lines>...
    )
ImportError: cannot import name 'FORMAT_NUMBER' from 'homeassistant.components.alarm_control_panel' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py)

**Comment by cyberkryten** [comment]
I've also still got this issue, updated to latest HA.

I notice there's another issue raised which is producing the same error https://github.com/lawtancool/hass-control4/issues/33

**Comment by deltamikeromeo** [comment]
I'm at a loss too. @lawtancool is this a known issue to you? Anything we can gather that might help?

> Anyone got any suggestions? I've worked around most of the issues caused by the C4 link being dead but I can't link to the alarm panel from both HA and my C4 system as it uses the same Com module.
> 
> I'll have to choose one or the other if this integration is never getting fixed/updated and I like having it within C4 when I'm using that at home or remotely.
> 
> The integration has failed on every version since it was raised - currently on 2025.7.1

**Comment by deltamikeromeo** [comment]
Hey @lawtancool 

I did some more digging into this, and I think I've pinpointed the source of the KeyError that's causing the 500 error.

The problem seems to be located in custom_components/control4/config_flow.py.

Specifically, this line is trying to log debug info for the alarm states:


`_LOGGER.debug(self.entry_data[CONF_ALARM_ARM_STATES])`

**The code directly accesses the alarm_arm_states key without first checking if it exists in self.entry_data.** Since my Control4 system doesn't have an alarm, this key is never created in my configuration, which results in the KeyError and stops the setup process.

**A check to verify the key exists before attempting to access it should resolve the crash for users without an alarm system.**

Hope this helps! 

CC: @cyberkryn

**Comment by mellis** [comment]
> > I do see the warning regarding the blocking call but my system seems to be functioning still with 1.3.0 and latest HA version.
> 
> [@mellis](https://github.com/mellis), You mention yours is still working. Do you have an alarm system in your Control4? I am curious if this is some KeyError stemming from the code not properly handling the absence of an alarm system in our Control4 configuration.

Yes, I do have an alarm system in Control4
